@startuml exercice

class NonElectronicDuck implements Duck{
    +quack(): void
    +swim(): void
}

class ElectronicDuck implements Duck {
    -_on: boolean
    +quack(): void
    +swim(): void
    +turnOn(): void
    +turnOff(): void
}

interface Duck {
    + swim()
    + quack()
}

class PoolManager {
    +run(): void
    -quack(Duck... ducks): void
    -swim(Duck... ducks): void
}

PoolManager --|> Duck

@enduml